version: '3.1'

services:
  db:
    image: mysql:8.4.0
    container_name: mysql-tupausanecesaria
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tupausanecesaria
